# Generated by Django 4.2 on 2023-04-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=10),
        ),
    ]
