# Generated by Django 4.2 on 2023-04-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='issue_title')),
                ('location', models.CharField(blank=True, max_length=1000, null=True, verbose_name='issue_location')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('issue_status', models.CharField(default=0, max_length=1, verbose_name='issue_status')),
                ('issue_image', models.ImageField(max_length=300, upload_to='Issue image')),
                ('solved_image', models.ImageField(max_length=300, null='True', upload_to='solve image')),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.userextra')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userextra')),
            ],
            options={
                'unique_together': {('user', 'report')},
            },
        ),
        migrations.CreateModel(
            name='SolvedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_image', models.ImageField(max_length=300, null=True, upload_to='solve image')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.report')),
            ],
            options={
                'unique_together': {('solved_image', 'report')},
            },
        ),
    ]
